import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    stockBar:false,
    stockTable:true,
  };

    const SISlice = createSlice({
    name: 'stockItem',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
      onBar: (state = initialState ) => {
        // Redux Toolkit allows us to write "mutating" logic in reducers. It
        // doesn't actually mutate the state because it uses the Immer library,
        // which detects changes to a "draft state" and produces a brand new
        // immutable state based off those changes
        state.stockBar = true;
      },
      offBar: (state = initialState) => {
        state.stockBar = false
      },
      onTable:(state = initialState) => {
        state.stockTable = true
      },
      offTable:(state = initialState) => {
        state.stockTable = false
      },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
  });
  export const { onBar, offBar, onTable, offTable } = SISlice.actions;
  
export default SISlice.reducer;